### ISSUE TITLE
RSpec 3 compatibility?

### ISSUE THREAD

**Issue by swrobel** [tpope/fivemat#29]
```
Deprecation Warnings:

 The Fivemat formatter uses the deprecated formatter interface not supported directly by RSpec 3.  To continue to use this formatter you must install the `rspec-legacy_formatters` gem, which provides support for legacy formatters or upgrade the formatter to a compatible version.  Formatter added at: vendor/bundle/gems/rspec-core-3.4.1/exe/rspec:4:in `<top (required)>'
```

**Comment by xaviershay** [comment]
Can you provide a repro? This works fine for most people, so maybe something in your setup code.

https://github.com/tpope/fivemat/blob/master/lib/fivemat.rb#L15
https://github.com/tpope/fivemat/blob/master/lib/fivemat/rspec3.rb

**Comment by swrobel** [comment]
Ok, I'm using this on a rails project, and here's the relevant section of my `Gemfile`:

```ruby
group :test do
  gem 'rspec-rails'
end
```

In that case, if I run the following (not sure if it's the ideal way to test, but the results are illuminating):

```
$ rails c test
Loading test environment (Rails 4.2.5)
irb(main):001:0> defined?(::RSpec::Core) && ::RSpec::Core::Version::STRING >= '3.0.0'
=> nil
irb(main):002:0> defined?(::RSpec::Core)
=> nil
irb(main):003:0> defined?(::RSpec::Rails)
=> "constant"
```

If I change my `Gemfile` to the following:
```ruby
group :test do
  gem 'rspec'
  gem 'rspec-rails'
end
```

Then it works as expected:
```
$ rails c test
Loading test environment (Rails 4.2.5)
irb(main):001:0> defined?(::RSpec::Core) && ::RSpec::Core::Version::STRING >= '3.0.0'
=> true
```

**Comment by xaviershay** [comment]
huh, that's weird. Linked up a PR that might fix, going to get feedback from other RSpec team.

Thanks for reporting!

**Comment by JonRowe** [comment]
Hi @swrobel can you confirm how you're actually running your specs? `rails c test` is just a Rails console and doesn't accurately reflect the environment that RSpec sees (as typically someone uses the `rspec` executable or the Rake task, both of which would load `rspec-core` first).

**Comment by swrobel** [comment]
@JonRowe I run them using `rspec` from the commandline. I just wanted to get a console so I could test your code for determining rspec version. I'd honestly never run `rails c test` before.

**Comment by JonRowe** [comment]
So do you see the deprecation warning when using `rspec` from the command line.

**Comment by swrobel** [comment]
Yes, that's what the initial report derived from

**Comment by JonRowe** [comment]
So how are you loading fivemat? As `RSpec::Core` will definitely be defined inside our executable, so there's something else going on...

**Comment by swrobel** [comment]
`rspec --format Fivemat` ... didn't realize you had an executable

**Comment by swrobel** [comment]
Ohhh, you mean the `rspec` executable. My `rspec` binstub is springified though, if that might affect things... I did try stopping spring & then running `rspec --format Fivemat` again and got the same deprecation warning.

**Comment by JonRowe** [comment]
Hmm, so this may be a side effect of using spring... Can you delete your spring binstub and try again?

**Comment by swrobel** [comment]
spring strikes again! With a bundler-generated binstub, it works fine, without a deprecation warning. With the springified binstub, I get the deprecation warning and the standard rspec progress-formatted output (the dots). Sorry for the false alarm...

**Comment by swrobel** [comment]
I suppose an issue could be filed for [spring-commands-rspec](https://github.com/jonleighton/spring-commands-rspec) but I'm not sure where to start...

**Comment by mattmartini** [comment]
I get the same error as OP when running rspec from guard + spork.
Rails 4.2.6
Using guard 2.14.1
Using guard-rails 0.8.0
Using guard-rspec 4.7.3
Using guard-spork 2.1.0
Using spork-rails 4.0.0

**Comment by tpope** [comment]
I think this was fixed by be3d421068dcde3bf012140fc7890cb15a96c7a0?

**Comment by mattmartini** [comment]
I'm using fivemat (1.3.5) which should be c250152 (one commit after be3d421) and I still see the broken behavior.

**Comment by mattmartini** [comment]
I created a demo RoR app to show the issue:

https://github.com/mattmartini/fivemat_issue29

Run guard and when you run specs the error msg is shown

**Comment by metalelf0** [comment]
Having the same issue. I suppose autoloading stuff somehow breaks the rspec version checking mechanism. @tpope , what do you think about releasing an rspec3-only version of this gem? Eventually in a separate branch so that users could still choose the master branch for retrocompatibility.

**Comment by mattmartini** [comment]
Point taken, I should've cleaned up my Gemfile and gotten rid of the stuff that doesn't matter.  I was trying to give you a look at the environment I was testing under.  

Would you be willing to look at it again if I clean out the gemfile?

**Comment by tpope** [comment]
That and everything else in the way. I don't think `uninitialized constant Features` is a Gemfile issue.

**Comment by mattmartini** [comment]
I just removed tons of cruft.  The original issue remains though, unless `rspec-legacy_formatters` gem is included it doesn't work.  Not sure what the `uninitialized constant Features` problem is, but I didn't see it when I did a fresh install of the app with a new rvm gemset.

**Comment by mattmartini** [comment]
I also just tried upgrading to `Rails` 4.2.10 (from 4.2.6) and `fivemat` 1.3.6 (from 1.3.5), with no change in behavior: `fivemat` works fine if the `rspec-legacy_formatters` gem is installed and doesn't if it is not.  I pushed these changes to the test app.

**Comment by JonRowe** [comment]
> `fivemat` works fine if the `rspec-legacy_formatters` gem is installed and doesn't if it is not.

FYI this is because the load order is making `fivemat` think RSpec 3 isn't installed.

**Comment by mattmartini** [comment]
Tom, as a note, since fivemat works when `rspec-legacy_formatters` gem is installed, this isn't a critical issue.  I have been using fivemat for months and really like it.  This issue shouldn't detract from the *amazing* vim plugins you have developed/are developing.

**Comment by mattmartini** [comment]
@JonRowe are you talking about the order of items in the `Gemfile`?  I did change the order of gems when I cleaned my `Gemfile` an hour ago, and there was no change in behavior.  
Or are you talking about something else?

**Comment by JonRowe** [comment]
RSpec warns about legacy formatters when they don't register themselves correctly, `fivemat` checks for the presence of a constant and the version string of rspec to determine this, and registers itself if it detects RSpec 3, if the constant is missing due to the order in which things are being loaded, it will not register itself correctly

**Comment by JonRowe** [comment]
This is not a Gemfile issue, but a require order issue.

**Comment by JonRowe** [comment]
Prehaps its time to release a major version bump that drops rspec 2 compatibility :)

**Comment by mattmartini** [comment]
The issue is with `rspec` 3 not `rspec 2`.

From the test app:
`rspec (`3.5.0)
`rspec-core` (3.5.4)
`rspec-legacy_formatters` (1.0.1)
`rspec-rails` (3.5.2)

**Comment by JonRowe** [comment]
No the issue is RSpec isn't being detected.

**Comment by JonRowe** [comment]
If you look at this, https://github.com/tpope/fivemat/blob/master/lib/fivemat.rb#L15 you'll see if the constant is missing (as it hasn't been loaded yet) then `fivemat` won't register itself correctly (https://github.com/tpope/fivemat/blob/master/lib/fivemat.rb#L22). If you place the require rails before fivemat that goes away.

**Comment by tpope** [comment]
The issue is with Guard. I just tried that repo with the first custom rspec formatter I could find, https://github.com/vbanthia/rspec_html_reporter, and it aborts on a LoadError. The only difference between it and us is it *doesn't* fall back to an RSpec 2 formatter, so it breaks entirely rather than issuing a warning.

Adding a `require 'rspec'` will work around the bug, but that will break for Minitest and Cucumber users.

I'd recommend opening a bug on guard-rspec about custom formatters.

**Comment by tpope** [comment]
Declaring an explicit rspec gem dependency is probably the easiest way to achieve that. The fact rspec-rails doesn't load rspec is kind of bonkers.

**Comment by JonRowe** [comment]
It does, https://github.com/rspec/rspec-rails/blob/9bd0e41bd7348844c8444208a3f4f3abfc44dce6/lib/rspec/rails.rb#L1

**Comment by JonRowe** [comment]
Hmm, but https://github.com/rspec/rspec-rails/blob/9bd0e41bd7348844c8444208a3f4f3abfc44dce6/lib/rspec-rails.rb doesn't... I wonder if requiring rspec-core in there would fix this...

**Comment by tpope** [comment]
I guess it makes sense. This file gets loaded into development so you probably don't want to pull in an entire test framework, just the glue like rake tasks.

**Comment by JonRowe** [comment]
I'd say prehaps you could `require 'rspec/core/version'` and rescue any `LoadError` that may occur, but that wouldn't force the loading of rspec... I mean it's not an issue when run from RSpec obviously...

**Comment by xaviershay** [comment]
weird, not obvious to me what requiring `rspec-rails` is supposed to do. I was expecting an alias of `rspec/rails` but it's totally different. Looking at history, found https://github.com/rspec/rspec-rails/pull/1678 - looks like it _used_ to load `rspec/core`. That's a revert of my proposed fix for this issue in https://github.com/rspec/rspec-rails/commit/994cb7afa8919c5f4560c8b765867b2aac15c192#diff-146ec820ea9e0eb2816387cc584a8695

**Comment by JonRowe** [comment]
@xaviershay @tpope nailed it on the head, it's the glue that adds the relevant "hey we're RSpec" to Rails, as bundler will autoload it and thats how you get the rake tasks generators etc in dev mode without loading all of the test environment
